root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/app main.go"
bin = "tmp/app"
include_ext = ["go", "html"]
exclude_dir = ["vendor", "node_modules", "tmp"]
delay = 1000

[log]
time = true

[color]
main = "yellow"

[include]
ext = ["go", "html"]
path = ["pages", "partials", "."]
